#!/bin/sh
# test installation of ump application program.
# kill ump processes
# exit with number of processes killed.  -number if failed while doing it.

# Initialize
help=0
version=0

# getopt  from /usr/lib/getopt/parse.bash
TEMP=`getopt -o hV --long help,version \
     -n 'killUmp' -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"
while true ; do
	case "$1" in
	        -h|--help)        help=1;           shift ;;
	        -V|--version)     version=1;        shift ;;
		--) shift ; break ;;
		*) echo "Internal error!" ; exit 1 ;;
	esac
done

if ( test $help -eq "1" )
then
   echo "usage"
   echo "  $0 [options]"
   echo "  options:"
   echo " -h,  --help         this screen"
   echo " -V,  --version      print version"
   echo "  Kill ump processes.  Exit with number of processes"
   echo "  killed.  -number if failed while doing it."
  exit 0;
fi

if ( test $version -eq "1" )
then
   echo '$Id: killUmp,v 1.1 2006/08/10 22:23:32 davegutz Exp davegutz $'
   echo "Written by Dave Gutz, Copyright (C) 2005"
   exit 0;
fi

# Check for UNIX
if ( test `which gpl2M 2>/dev/null|wc -l` -gt 0 )
then
   psopt="-ef"
   killopt=9
else
   psopt="ax"
   killopt="s 9"
fi

# Kill streamery first
if ( test "$srcdir " = " " )
then
   killSty
else
   $srcdir/killSty
fi
statSty=$?
if ( test $statSty -lt 0 )
then
   echo "ERROR($0):  could not kill streamery processes."
   sleep 5
   exit $statSty
fi

# Exit if none to kill
numump=`ps "$psopt" | grep "ump -" | sed '/grep/d' |
 sed '/gnome-terminal/d' |  wc -l`
if ( test $numump -eq 0 )
then
   echo "MESSAGE($0): There are no running ump processes."
   sleep 2
   exit 0
fi

# Make a list of running umps
if ( test `which gpl2M 2>/dev/null|wc -l` -gt 0 )
then
   umppid=`ps "$psopt"|grep "ump -" | sed '/grep/d' | sed '/gnome-terminal/d' | awk '{print $2}'`
else
   umppid=`ps "$psopt"|grep "ump -" | sed '/grep/d' | sed '/gnome-terminal/d' |awk '{print $1}'`
fi

# Kill them all
if ( test x"$umppid" != x )
then
for i in $umppid
do
   kill -$killopt $i
done
sleep 2
echo "MESSAGE($0): be sure to run 'ipcs shm' or 'ipcs -m' then 'ipcrm shm <shmid>' or 'ipcrm -m <shmid>' as needed"
fi
numump=`ps "$psopt" | grep "ump -" | sed '/grep/d' | sed '/gnome-terminal/d' | wc -l`
if ( test $numump -gt 0 )
then
   echo "WARNING($0): still there are running ump process."
   numump=`echo $numump | awk '{printf"-%s",$1}'`
else
   echo "MESSAGE($0): stopped all running ump process."
fi
sleep 2
exit $numump
